### ISSUE TITLE
Analyzer service is sending auth headers to a ES AWS instance without auth in place

### ISSUE THREAD

**Issue by mlarrea** [reportportal/service-auto-analyzer#121]
Since version 5.5 the ES client is sending HTTP auth headers to the ES endpoint, this causes the remote throwing the following error when there is not basic auth, i.e. when you have a ES instance running in AWS OpenSearch publicly available but access control based on IP/CIDRs:

analyzerApp.amqpHandler - ERROR - AuthorizationException(403, '{"message":"Authorization header requires \'Credential\' parameter. Authorization header requires \'Signature\' parameter. Authorization header requires \'SignedHeaders\' parameter. Authorization header requires existence of either a \'X-Amz-Date\' or a \'Date\' header. Authorization=Basic Og=="}')

To reproduce, reportportal v > 5.5 installed on AWS K8s cluster and a ES instance with no basic auth.

This may be related to this pending PR:
https://github.com/reportportal/service-auto-analyzer/pull/113

![auth-error](https://user-images.githubusercontent.com/24795563/165324959-2a462121-05b4-4785-bb0f-a43859117651.png)

**Comment by gnazgit** [comment]
Hi Team, any ETA on the pull request? We are facing the same issue, it will be great if this can be considered for the upcoming release. Thanks!
@HardNorth @avarabyeu

**Comment by mlarrea** [comment]
Hi Vadzim, many thanks for the quick response and fix.

**Comment by gnazgit** [comment]
Thanks @HardNorth for the quick fix.

**Comment by HardNorth** [comment]
@gnazgit I believe, yes.

**Comment by ajoux-accor** [comment]
Same issue for us
