### ISSUE TITLE
Allow https connections to S3

### ISSUE THREAD

**Issue by vitalii-b3** [reportportal/service-auto-analyzer#136]
We use S3 instead of minio and currently there is no variable that can enable https connections to S3. Looks like this line needs to be changed to allow us to enable https S3 connections

https://github.com/reportportal/service-auto-analyzer/blob/ae295dc172d5fb172b4c7c8f065fe7e251d3f756/commons/object_saving/minio_client.py#L37

**Comment by HardNorth** [comment]
Should be fixed in: https://github.com/reportportal/service-auto-analyzer/releases/tag/5.11.0
