### ISSUE TITLE
This does not work with single bucket mode / s3 at all because the bucket names are hardcoded to project name

### ISSUE THREAD

**Issue by sharkymcdongles** [reportportal/service-auto-analyzer#149]
**Describe the bug**
analyzer always tries to upload to project name buckets and cannot be configured to upload to a single bucket at a particular path.

**Expected behavior**
Same behavior as the other services with bucketname respected.

**Comment by tomikonio** [comment]
Hi :slightly_smiling_face: 
Is it still the case?
We would like to switch from minio to S3 eventually.
What are the implications of the analyzer service using an ephemeral `Filesystem` storage?

**Comment by yoavws** [comment]
Hi we faced this issue as well.
Is there any update here? 👍

**Comment by kondratm** [comment]
Same issue here, can it be prioritized please?

**Comment by yoavws** [comment]
Is there any update on this issue? we want to migrate to a RP +S3 deployment.
also any workaround?

**Comment by HardNorth** [comment]
Please use the latests Release: https://github.com/reportportal/reportportal/releases/tag/24.2.2
With this you can specify a path in 'ANALYZER_BINSTORE_BUCKETPREFIX' variable.
According to the documentation:

> The prefix for buckets which will be transformed to project folder by appending Project ID, E.G. `prj-2`. It can contain root path, like: `my-bucket/reportportal/prj-`, then the service will operate in single bucket mode and will put everything to `my-bucket` bucket, under `reportportal/prj-2` (for default project of default user) path.

**Comment by HardNorth** [comment]
@dstewart-kb4, you can just move everything from analyzer's buckets to corresponding project folders, it shouldn't conflict.
Pay attention on this bug: https://github.com/reportportal/service-auto-analyzer/issues/196
