### ISSUE TITLE
Receive ERROR - Failed to process launches when attempting to analyze a project

### ISSUE THREAD

**Issue by mmalandra-kb4** [reportportal/service-auto-analyzer#33]
Full error (not sure how to get more detailed error logging).

```
2020-08-05T16:53:32.211-04:00 | 2020-08-05 20:53:32,210 - analyzerApp.amqpHandler - ERROR - Failed to process launches
2020-08-05T16:53:32.211-04:00 | 2020-08-05 20:53:32,210 - analyzerApp.amqpHandler - ERROR - 'hits'
```

Initially the analyzer works, but after a while it begins throwing this error. I can consistently reproduce it. We're running the analyzer on C# logs.

**Comment by MariyaIvanina** [comment]
@mmalandra-kb4 Hi! This could have happened if you didn't regenerate the index after moving from one version of Analyzer to another. Could you, please, try to generate index in the settings of Auto analyzer section and then check whether the analysis works?

**Comment by mmalandra-kb4** [comment]
Interestingly enough, I can't select the options. It has the buttons grayed out. I'm not sure how the UI handles determining if it is running, but i can see that the ES service and Auto-analyze services are up and running on aws.

**Comment by MariyaIvanina** [comment]
If these buttons are grayed out, this is not on the analyzer side. We saw such a problem because of misconfiguration of traefik. You can address this problem to our slack chat https://reportportal-slack-auto.herokuapp.com/ . They could help with this, I saw that someone solved such an issue when returned to traefik 2.0.5 version.

**Comment by mmalandra-kb4** [comment]
thanks. I'll look there and report back once that is solved if this continues.

**Comment by mmalandra-kb4** [comment]
Issue was resolved after fixing the index service.
