### ISSUE TITLE
Ability to set MINIO_REGION environment variable

### ISSUE THREAD

**Issue by pako88** [reportportal/service-auto-analyzer#43]
When using S3 rather than minio it is necessary to set the aws region. For this it would be helpful to have an environment variable `MINIO_REGION`,

In the reportportal api service i can for example set following environment variable: `RP_BINARYSTORE_MINIO_REGION`

**Comment by MariyaIvanina** [comment]
Hi, thanks for reporting this issue. I've added ANALYZER_BINARYSTORE_MINIO_REGION environmental variable, so you can set the region now. This is available in 5.3.4 version, I've just released it. You can also see other available environmental variables here https://github.com/reportportal/service-auto-analyzer/blob/develop/README.md

**Comment by ivan-sukhomlyn** [comment]
@MariyaIvanina Hello,
first of all, thanks for your work 👍 

I would like to ask if you could check the working with the MinIO client in a non-default(us-east-1) region where the S3 bucket used instead of the MinIO server.

The service-auto-analyzer logs:
```
2021-03-26 11:36:54,855 - analyzerApp.minioClient - ERROR - InvalidArgumentError: message: Configured region us-west-2, requested us-east-1
2021-03-26 11:36:54,918 - analyzerApp.minioClient - ERROR - InvalidArgumentError: message: Configured region us-west-2, requested us-east-1
2021-03-26 11:36:54,923 - analyzerApp.amqpHandler - ERROR - Failed to publish result
2021-03-26 11:36:54,923 - analyzerApp.amqpHandler - ERROR - A non-string value was supplied for self.routing_key
```

version is **5.3.5**

configuration:
```
» kubectl  get pod -o yaml reportportal-analyzer-7bbf57ccd5-mts2m | grep MINIO -A 1
    - name: MINIO_SHORT_HOST
      value: {{ s3 bucket name }}.s3.us-west-2.amazonaws.com
--
    - name: ANALYZER_BINARYSTORE_MINIO_REGION
      value: us-west-2
```

**Comment by MariyaIvanina** [comment]
@ivan-sukhomlyn Thanks for your nice words. I've fixed region specification, it turned out that region should be specified not only on minio client initialization, but also on bucket creation, so now I've checked on my own s3 bucket with "us-west-2" and it worked fine, so in 5.4 version you'll be able to use this functionality.

**Comment by ivan-sukhomlyn** [comment]
Thanks @MariyaIvanina. Looking forward to a new release
