### ISSUE TITLE
Wrong AA classification

### ISSUE THREAD

**Issue by talmoshe24** [reportportal/service-auto-analyzer#77]
I'm using reportportal 5.4 with agent-java-junit 4
In two different cases, the AA tagged a failure to an existing issue (such as "System Issue") for a different test with a different log, where both had the same exception inside.
The AA configuration is the default one - classic mode, where it should evaluate all log lines for 95% match

Is there any information on how the AA makes the decision when tagging an issue as an existing one?

**Comment by MariyaIvanina** [comment]
@talmoshe24 Hi! Could you please provide the logs, the analysis results for them and what you would expect from analyzer to do in this case? This will help to understand your issue to the full extent. Thanks!

**Comment by talmoshe24** [comment]
[](url)

**Comment by talmoshe24** [comment]
Test that was tagged by AA:
[https://www.idrive.com/idrive/sh/sh?k=r4e9i3l1e1](url)

Based on this one:
[https://www.idrive.com/idrive/sh/sh?k=d1s4q5v9s5](url)

**Comment by MariyaIvanina** [comment]
@talmoshe24 I can't access your links due to security reasons, could you please copy text and send it here?

**Comment by talmoshe24** [comment]
![AA1](https://user-images.githubusercontent.com/17446962/126446380-d8733298-91c5-4b90-a61e-d1198c7b2147.PNG)
![AA2](https://user-images.githubusercontent.com/17446962/126446405-fadf1cef-1b45-4236-832b-43728f2da766.PNG)

**Comment by MariyaIvanina** [comment]
Are these logs all the same for the second test item with System issue? Because they couldn't match by those logs, could you show other error logs in the the second test item?

**Comment by talmoshe24** [comment]
The bottom log of the second item:
![AA3](https://user-images.githubusercontent.com/17446962/126450589-a95b6938-e0ca-42ec-b5e4-b45c76b4eb93.PNG)

**Comment by MariyaIvanina** [comment]
I see, so they matched by the log "[main] - << 0 >> woke to: {} ..." and the match >= 95%. We match test items by any log with the stacktrace (or if you don't have one, we should match by all available small logs). As far as we don't know which big log is the one you want to find by, we match them by any big log within the threshold you specified. If your log isn't the one you want to make a decision by, could you somehow not to send to Report portal?

**Comment by talmoshe24** [comment]
The full log (not only the error logs) is completely different, as the 2 tests are different. Only one stack trace matches.
How can I configure the system to go over the full log of the tests (and match 95% of it) instead of a single stack trace?

**Comment by MariyaIvanina** [comment]
I see your point, at this moment we don't have such setting, so I'll think how this can be added to the model or the settings in the next version of report portal. I'm sorry for inconvenience!

**Comment by talmoshe24** [comment]
I see thank you for your answer
So just to be clear - is the classification based only on the error message?

**Comment by MariyaIvanina** [comment]
Yes, classification is based only on error or fatal logs.

**Comment by talmoshe24** [comment]
@MariyaIvanina is it possible to add it as feature request?

**Comment by MariyaIvanina** [comment]
I'm adding it to the scope of the tasks and will try to solve it. I'll notify when the discussion about this task is ready and we agree on the release plan for this task.

**Comment by talmoshe24** [comment]
Thanks, @MariyaIvanina is there a task item to follow?

**Comment by MariyaIvanina** [comment]
Actually, no, we use our internal jira, but I'll notify you as soon as possible)

**Comment by MariyaIvanina** [comment]
@talmoshe24 Hi! We've added a setting "All logs with 3 or more log lines should match" in the Auto-analysis settings, so you will be able to switch it on and this should help with your situation. This change is in 5.6 version, it's released, but other RP images are not released. When 5.6 is relased for the whole RP, you'll be able to use these changes. Hope it will help!

**Comment by talmoshe24** [comment]
@MariyaIvanina Thanks for your help! 
I just upgraded to 5.6.0, will keep you posted
